[123] Fixing broken import from uds module
CaringCaribou/caringcaribou pull request #125
Opened 2024-08-22 20:10 UTC by n135c10r

Its fixing [this](https://github.com/CaringCaribou/caringcaribou/issues/123) issue.

I fixed only broken import with its usage, but i think both `seed_randomness_fuzzer` and `delay_fuzzer` could get some refactor.

2024-08-23 12:06 UTC, kasperkarlsson requested changes
The suggested change passes the whole response to the `print_negative_response_code` rather than the (integer) NRC from the response, which will lead to a runtime error 😅

2024-08-23 18:30 UTC, n135c10r commented
Ok, I think it should work now 🙈 
Maybe there should be an additional function for retrieving the NRC code from the response?

2024-08-25 06:22 UTC, kasperkarlsson approved these changes
This fixes the issue! Just as you say, adding a function to the `uds` module which retrieves the NRC from a message would be a good idea.

2024-08-25 06:22 UTC, kasperkarlsson commented on caringcaribou/modules/uds_fuzz.py
> +                        print_negative_response_code(nrc)
Yep - this looks great! 👍

2024-08-25 06:22 UTC, merged